//ERRORS
export const GET_ERRORS = 'GET_ERRORS';

//PACKAGES 
export const FETCH_PACKAGES = 'FETCH_PACKAGES';
export const BUY_PACKAGE = 'BUY_PACKAGE';
export const SET_CURRENT_PERSONNEL = 'SET_CURRENT_PERSONNEL';
export const SET_CURRENT_AGENT = 'SET_CURRENT_AGENT';
export const FETCH_CUSTOMER_DETAILS = 'FETCH_CUSTOMER_DETAILS';
export const FETCH_CUSTOMER = 'FETCH_CUSTOMER';
export const AGENT_REGISTER_CUSTOMER = 'AGENT_REGISTER_CUSTOMER';
export const DISCONNECT_CUSTOMER = 'DISCONNECT_CUSTOMER';


// CREDIT
export const BUY_CREDIT = 'BUY_CREDIT';
export const FETCH_CREDIT = 'FETCH_CREDIT';
export const GET_AGENT_FLOAT = 'GET_AGENT_FLOAT';
export const GET_CUSTOMER_PAYMENTS = 'GET_CUSTOMER_PAYMENTS';

// reset password
export const GET_OTP = 'GET_OTP';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// lock customer 
export const LOCK_CUSTOMER = 'LOCK_CUSTOMER';
export const FETCH_LOCKED_CUSTOMERS = 'FETCH_LOCKED_CUSTOMERS';